### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by lendres-ai** [RaduTM-spec/DeepUnity#1]
Hey 👋 , great project! Could be very useful for what I am trying to do: ML learning in unity build, mobile specifically. I am trying to install the package, I found some instructions on how to install custom unity packages but it seems to require a package.json. Could you help me out? Thanks :)

**Comment by lendres-ai** [comment]
I just used your entire project, everything works great. I will just create my Scene in there for now :)

**Comment by smtmRadu** [comment]
Hi. Note that I let the repository public before the alpha version for learning purposes only. You can train agents with it and do machine learning stuff using the library (highly recommended for pc with GPU), but you will not be able to build your project due the usage of Unity Editor library (until alpha version i have to enclose code in UNITY_EDITOR regions. To add DeepUnity to your project, just drag and drop the DeepUnity and Editor folders inside your Assets folder.
